CREATE TABLE PROVEEDORES
(NUMERO INT NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
DOMICILIO VARCHAR(15) NOT NULL,
LOCALIDAD VARCHAR(12),
PRIMARY KEY (NUMERO));


CREATE TABLE PRODUCTOS
(PNRO INT NOT NULL,
PNOMBRE VARCHAR(20) NOT NULL,
PRECIO INT NOT NULL,
TAMAÑO VARCHAR(20),
LOCALIDAD VARCHAR(12) NOT NULL,
PRIMARY KEY (PNRO));

CREATE TABLE "PROV-PROD"
(NUMERO INT NOT NULL,
PNRO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY (NUMERO, PNRO),
FOREIGN KEY (NUMERO) REFERENCES PROVEEDORES
(NUMERO),
FOREIGN KEY (PNRO) REFERENCES PRODUCTOS (PNRO));

-- Bulk Inserts for PROVEEDORES table
INSERT INTO PROVEEDORES (NUMERO, NOMBRE, DOMICILIO, LOCALIDAD) VALUES 
(1, 'Proveedor1', 'Domicilio1', 'Localidad1'),
(2, 'Proveedor2', 'Domicilio2', 'Localidad2'),
(3, 'Proveedor3', 'Domicilio3', 'Localidad3');

INSERT INTO PROVEEDORES (NUMERO, NOMBRE, DOMICILIO, LOCALIDAD) VALUES 
(4, 'Proveedor4', 'Domicilio4', 'Wilde'),
(5, 'Proveedor5', 'Domicilio5', 'Lanus'),
(6, 'Proveedor6', 'Domicilio6', 'Wilde');

INSERT INTO PROVEEDORES (NUMERO, NOMBRE, DOMICILIO, LOCALIDAD) VALUES 
(7, 'Proveedor7', 'Domicilio7', 'Capital');
INSERT INTO PROVEEDORES (NUMERO, NOMBRE, DOMICILIO, LOCALIDAD) VALUES (8, 'Proveedo8', 'Domicilio8', 'Avellaneda');
-- Bulk Inserts for PRODUCTOS table
INSERT INTO PRODUCTOS (PNRO, PNOMBRE, PRECIO, TAMAÑO, LOCALIDAD) VALUES 
(1, 'Producto1', 100, 'Grande', 'Localidad1'),
(2, 'Producto2', 200, 'Mediano', 'Localidad2'),
(3, 'Producto3', 300, 'Pequeño', 'Localidad3');

INSERT INTO PRODUCTOS (PNRO, PNOMBRE, PRECIO, TAMAÑO, LOCALIDAD) VALUES 
(4, 'Producto4', 450, 'Mediano', 'Capital');
INSERT INTO PRODUCTOS (PNRO, PNOMBRE, PRECIO, TAMAÑO, LOCALIDAD) VALUES (6, 'Producto6', 600, 'Pequeño', 'Localidad6');
INSERT INTO PRODUCTOS (PNRO, PNOMBRE, PRECIO, TAMAÑO, LOCALIDAD) 
VALUES (7, 'Producto7', 900, 'Pequeño', 'Lanus');

-- Bulk Inserts for "PROV-PROD" table
INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES 
(1, 1, 10),
(2, 2, 20),
(3, 3, 30);

INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES 
(1, 3, 3),
(2, 1, 13),
(1, 2, 44);

INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES 
(7, 4, 255);
INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES 
(2, 4, 300);
INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES (7, 6, 60);
INSERT INTO "PROV-PROD" (NUMERO, PNRO, CANTIDAD) VALUES (8, 3, 287);